name: Bug Report (General)
description: 'Create a report to help us improve'
body:
  - type: markdown
    attributes:
      value: 'Please note your issue will be closed without comment if do not fill out the issue checklist and provide ALL the requested information.'
  - type: checkboxes
    attributes:
      label: Checks
      description: Please verify that you've followed these steps.
      options:
        - label: I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/) or in [GitHub Discussions](https://github.com/CiroZDP/opencraft/discussions).
          required: true
        - label: I updated to the latest OpenCraft version.
          required: true
  - type: textarea
    attributes:
      label: 'Describe the bug (be clear and concise)'
      description: 'Put every detail you can specify. This will help solve your issue more easily'
    validations:
      required: true
