blank_issues_enabled: false
contact_links:
  - name: Let the community guide you!
    url: https://github.com/CiroZDP/opencraft/discussions
    about: Have a question? The quickest way to get help is on OpenCraft's GitHub Discussions!
