name: Download for Windows
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-windows
  cancel-in-progress: true

jobs:
  x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install packages
        run: |
          sudo apt-get -y install \
            gcc-mingw-w64-i686 cmake

      - name: Compile
        shell: bash
        id: compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DTARGET_WINDOWS=ON -DTARGET_WINDOWS_32=ON
          cmake --build .

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/oc_win32.exe'
          DEST_NAME: 'OpenCraft-x32.exe'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://img.icons8.com/color/512/windows-11.png'
          title: 'Windows x32 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/CiroZDP/opencraft/actions/workflows/windows.yml) to see the latest version!'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://img.icons8.com/color/512/windows-11.png'
          title: 'Windows x32 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/CiroZDP/opencraft/actions/workflows/windows.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'

  x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get -y install \
            gcc-mingw-w64-x86-64 cmake

      - name: Compile
        shell: bash
        id: compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DTARGET_WINDOWS=ON -DTARGET_WINDOWS_64=ON
          cmake --build .

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/oc_win64.exe'
          DEST_NAME: 'OpenCraft-x64.exe'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://img.icons8.com/color/512/windows-11.png'
          title: 'Windows x64 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/CiroZDP/opencraft/actions/workflows/windows.yml) to see the latest version!'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://img.icons8.com/color/512/windows-11.png'
          title: 'Windows x64 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/CiroZDP/opencraft/actions/workflows/windows.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'
